### ISSUE TITLE
Black canvas until you move/resize the app window

### ISSUE THREAD

**Issue by vyo** [fireblade-engine/ecs-demo#1]
Just a heads up for anybody wondering why the canvas is blank/black on app start on Mac OS Mojave; it's basically a bug in the underlying SDL2 and is being tracked here: https://bugzilla.libsdl.org/show_bug.cgi?id=4272

system info:
 - sdl2@2.0.8
 - macos@10.14.1

**Comment by ctreffs** [comment]
This problem seems to be resolved  with **sdl2/2.0.9** (checked via `brew list sdl2`) and **macOS Mojave 10.14.2**.
@vyo please confirm.

**Comment by vyo** [comment]
can confirm the fix for:
 - sdl@2.0.9
 - macos@10.14.1

thanks for version heads up!
