### ISSUE TITLE
Can't find sdl2 on Linux

### ISSUE THREAD

**Issue by kevinkleine** [fireblade-engine/ecs-demo#25]
Building generates the following error `error: 'ecs-demo': product 'SDL2' required by package 'ecs-demo' target 'SDLKit' not found.` even though `sdl2-2.30.1-1` is present on the system.

OS Manjaro Linux 23.1.3
Swift v5.9.2

**Comment by pusewicz** [comment]
@ctreffs What's the best way to fix this issue?

**Comment by igorkravchenko** [comment]
@kevinkleine @pusewicz Hopefully https://github.com/fireblade-engine/ecs-demo/pull/27 addresses the issue.
